### ISSUE TITLE
Error on vagrant up on master.

### ISSUE THREAD

**Issue by millidavids** [CirrusMio/streakers#14]
![image](https://cloud.githubusercontent.com/assets/4100184/5621436/7b2e5b36-9503-11e4-9c6a-dcd3a3764245.png)

**Comment by chaserx** [comment]
hmm.

**Comment by chaserx** [comment]
if you copy those commands, they work when in the vm.

**Comment by chaserx** [comment]
I'm on this...

**Comment by chaserx** [comment]
fixed.

**Comment by millidavids** [comment]
yeah, just wanted to bring this to light

**Comment by chaserx** [comment]
should all be fixed up now.
